name: Publicar Structurizr Site

on:
  push:
    branches: [ main ]
    paths:
      - '**.dsl'
      - '.github/workflows/**' # Para que corra si arreglas este archivo

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Bajamos tu código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Generamos el sitio Web Estático
      # Usamos directamente la imagen de Docker de Avisi (más robusto)
      - name: Generar Sitio HTML
        uses: avisi-cloud/structurizr-site-generatr@v1
        with:
          # Argumentos: generate-site -w [tu archivo] -o [carpeta salida]
          args: generate-site -w workspace.dsl -o public

      # 3. Publicamos la carpeta 'public' en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public