name: Publicar Documentacion C4

on:
  push:
    branches: [ main ]
    paths:
      - '**.dsl'
      - '.github/workflows/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- NUEVO PASO: CREAR LA CARPETA ---
      # Creamos la carpeta 'public' explícitamente para que Java no falle
      - name: Crear carpeta de salida
        run: mkdir -p public

      - name: Generar Sitio con Structurizr Site Generatr
        uses: docker://ghcr.io/avisi-cloud/structurizr-site-generatr:latest
        with:
          # Ahora sí encontrará la carpeta 'public'
          args: generate-site -w workspace.dsl -o public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public